[default]
address = "0.0.0.0"

[default.databases.analytics]
url = "db.sqlite"

[release]
port = 4430

[release.tls]
certs = "/etc/letsencrypt/live/brandond.nl/fullchain.pem"
key = "/etc/letsencrypt/live/brandond.nl/privkey.pem"
